language: dart

dart:
  - dev

dart_task:
  - test: --platform vm,chrome

matrix:
  include:
    - dart: dev
      dart_task:
        dartanalyzer: --fatal-infos --fatal-warnings .
    - dart: dev
      dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
