include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    comment_references: ignore # too many false positives

linter:
  rules:
    - prefer_expression_function_bodies
