include: package:pedantic/analysis_options.yaml
analyzer:
  language:
    strict-casts: true

linter:
  rules:
  - avoid_dynamic_calls
  - prefer_equal_for_default_values
  - prefer_generic_function_type_aliases
  - prefer_typing_uninitialized_variables
  - slash_for_doc_comments
  - unnecessary_const
  - unnecessary_new
